#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"envoy"}})
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #@overlay/match missing_ok=True
    external-dns.alpha.kubernetes.io/hostname: #@ "*.apps.{},*.sso.{},*.monitoring.{},*.management.{}".format(data.values.domain, data.values.domain, data.values.domain, data.values.domain)

#@overlay/match by=overlay.subset({"kind":"CustomResourceDefinition"}),expects="0+"
---
#@overlay/remove
status:

#! #@overlay/match by=overlay.subset({"kind":"Job"}),expects="0+"
#! ---
#! #@overlay/remove