#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: letsencrypt
  namespace: kapp-controller
  annotations:
    kapp.k14s.io/change-rule.1: "delete before deleting gitops.tanzu.vmware.com/cert-manager"
    kapp.k14s.io/change-rule.2: "upsert after upserting gitops.tanzu.vmware.com/cert-manager"
spec:
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/letsencrypt/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        #@ for secretRef in data.values.letsencrypt_secretRef:
        - secretRef:
            name: #@ secretRef
        #@ end 
  deploy:
  - kapp: {}