#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: monitoring
  namespace: kapp-controller
spec:
  serviceAccountName: kapp-controller-clusteradmin
  fetch:
  - git:
      url: #@ data.values.git_url
      ref: #@ data.values.git_branch
      subPath: workload/monitoring/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        #@ for secretRef in data.values.monitoring_secretRef:
        - secretRef:
            name: #@ secretRef
        #@ end 
  deploy:
  - kapp: {}