#@data/values
---
git_url: https://code.afcmade.com/chrysalis/tkg-clusters.git
git_branch: origin/default
git:
  secretRef: workload-git-secret

contour_secretRef:
- domain-values

kuard_secretRef:
- domain-values
- kuard-client-values

externaldns_secretRef:
- certmanager-values
- aws-values
- external-dns-values

dex_secretRef: 
- domain-values
- grafana-client-values
- github-client-values
- dex-saml-values
- sonarqube-client-values
- kuard-client-values

monitoring_secretRef:
- domain-values
- grafana-client-values

letsencrypt_secretRef:
- domain-values
- certmanager-values

knative_secretRef:
- domain-values

gangway_secretRef:
- domain-values
- gangway-values

kiam_secretRef:
- kiam-values
- aws-values