#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: Namespace
metadata:
  name: workload-clusters
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: workload-clusters
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workload-clusters
  namespace: workload-clusters
  annotations:
    kapp.k14s.io/disable-wait: "true"
spec:
  serviceAccountName: workload-sa
  fetch:
  - git:
      url: #@ data.values.git.url
      ref: #@ data.values.git.branch
      subPath: management-cluster/workload/manifests
  template:
  - ytt:
      ignoreUnknownComments: true
      inline:
        pathsFrom:
        #@ for secretRef in data.values.workload_secretRef:
        - secretRef:
            name: #@ secretRef
        #@ end 
  deploy:
  - kapp: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: workload-role-binding
  namespace: workload-clusters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-role
subjects:
- kind: ServiceAccount
  name: workload-sa
  namespace: workload-clusters
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: workload-role
  namespace: workload-clusters
rules:
- apiGroups:
  - kappctrl.k14s.io
  - cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  - controlplane.cluster.x-k8s.io
  - bootstrap.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get