---
apiVersion: v1
kind: Secret
metadata:
  name: workload-config-secrets
  namespace: workload-clusters
stringData:
  auth-secrets.yaml: |
    #@data/values
    ---
    auth:
      oidc-client-id: REMOVED
      oidc-issuer-url: https://example.auth0.com
      oidc-username-claim: email
      oidc-groups-claim: groups
---
apiVersion: v1
kind: Secret
metadata:
  name: workload-git-secrets
  namespace: workload-clusters
stringData:
  git-secrets.yaml: |
    #@data/values
    ---
    git:
      url: https://code.afcmade.com/chrysalis/tkg-clusters.git
      branch: origin/master